[[overview]]
= Spring Framework 概览
:toc: left
:toclevels: 1
:docinfo1:

Spring 使创建 Java 企业应用程序变得容易。
它提供了在企业环境中使用 Java 语言所需的一切，
并支持 Groovy 与 Kotlin 作为 JVM 上的替代语言，
并可以根据应用程序的需求灵活地创建多种体系结构。
从 Spring Framework 5.1 开始，Spring 需要 JDK 8+（Java SE 8+），
并提供对 JDK 11 LTS 的现成支持。
建议将 Java SE 8 更新 60 作为 Java 8 的最低补丁版本，但通常建议使用最新的补丁版本。

Spring 支持广泛的应用程序场景。
在大型企业中，应用程序通常存在很长时间，
并且必须在升级周期不受开发人员控制的 JDK 与应用程序服务器上运行。
其他服务器则可以作为单个 jar 运行，并且服务器可以嵌入云环境中。
还有一些可能是不需要服务器的独立应用程序（例如批处理或集成工作负载）。

Spring是开源的。
它拥有一个庞大而活跃的社区，可以根据各种实际用例提供持续的反馈。
这帮助 Spring 在很长一段时间里成功地进化。




[[overview-spring]]
== 我们所说的“Spring”

术语“Spring”在不同的上下文中表示不同的事物。
它可以用来指代 Spring Framework 项目本身，而这一切都是从这里开始的。
随着时间的流逝，其他 Spring 项目已经建立在 Spring Framework 之上。
通常，当人们说“Spring”时，它们表示整个项目系列。
本参考文档重点关注基础：Spring Framework 本身。

Spring 框架分为多个模块。
应用程序可以选择所需的模块。
core 容器的模块是核心，包含配置模型与依赖项注入机制。
除此之外，Spring 框架还为不同的应用程序体系结构提供了基础支持，包括消息传递、事务性数据与持久化以及 Web。
它还包括基于 Servlet 的 Spring MVC Web 框架，
以及并行的 Spring WebFlux 反应式 Web 框架。

关于模块的说明：Spring 的框架 jar 允许部署到 JDK 9 的模块路径（“Jigsaw”）。
为了在启用 Jigsaw 的应用程序中使用，Spring Framework 5 jar 附带了“自动模块名称”清单条目，
这些清单条目定义了独立于 jar 构件的稳定语言级别的模块名称
（“ spring.core”、“ spring.context”等）
（jar 遵循相同的命名模式，用“-”代替“.”，例如：“spring-core”与“spring-context”）。
当然，Spring 的框架 jar 可以在 JDK 8 与 9+ 的类路径上正常工作。




[[overview-history]]
== Spring 的历史与 Spring Framework

响应于早期 https://zh.wikipedia.org/wiki/Jakarta_EE[J2EE]
规范的复杂性，Spring 于 2003 年应运而生。
尽管有些人认为 Java EE 与 Spring 竞争，但 Spring 实际上是 Java EE 的补充。
Spring 编程模型不包含 Java EE 平台规范。
相反，它与 EE 伞中精心选择的各个规范集成在一起：

* Servlet API（ https://jcp.org/en/jsr/detail?id=340[JSR 340] ）
* WebSocket API（ https://www.jcp.org/en/jsr/detail?id=356[JSR 356] ）
* 并发工具类（ https://www.jcp.org/en/jsr/detail?id=236[JSR 236] ）
* JSON 绑定 API（ https://jcp.org/en/jsr/detail?id=367[JSR 367] ）
* Bean 验证（ https://jcp.org/en/jsr/detail?id=303[JSR 303] ）
* JPA（ https://jcp.org/en/jsr/detail?id=338[JSR 338] ）
* JMS（ https://jcp.org/en/jsr/detail?id=914[JSR 914] ）
* 以及必要时用于事务协调的 JTA/JCA 设置。

Spring 框架还支持依赖注入（JSR 330）
（ https://www.jcp.org/en/jsr/detail?id=330[JSR 330] ）与通用注解
（ https://jcp.org/en/jsr/detail?id=250[JSR 250] ）规范，
应用程序开发人员可以选择使用这些规范来代替 Spring 框架提供的特定于 Spring 的机制。

从 Spring Framework 5.0 开始，Spring 至少需要 Java EE 7 级别（例如：Servlet 3.1+、JPA 2.1+）
——同时在运行时遇到 Java EE 8 级别
（例如：Servlet 4.0、JSON 绑定 API）的同时提供与较新 API 的现成集成。
这使 Spring 完全兼容例如：Tomcat 8 与 9、WebSphere 9 与 JBoss EAP 7。

随着时间的流逝，Java EE 在应用程序开发中的作用已经演变。
在 Java EE 与 Spring 的早期，创建了应用程序以将其部署到应用程序服务器。
如今，借助 Spring Boot，可以以对开发人员与云友好的方式创建应用程序，
并嵌入 Servlet 容器并对其进行微不足道的更改。
从 Spring Framework 5 开始，WebFlux 应用程序甚至不直接使用 Servlet API，
并且可以在非 Servlet 容器的服务器（例如 Netty）上运行。

Spring 继续创新与发展。
除了 Spring Framework，还有其他项目，
例如：Spring Boot、Spring Security、Spring Data、Spring Cloud、Spring Batch 等。
请记住，每个项目都有自己的源代码存储库，问题跟踪程序与发布节奏，这一点很重要。
有关 Spring 项目的完整列表，请参见 https://spring.io/projects[spring.io/projects]。




[[overview-philosophy]]
== 设计理念

在学习框架时，重要的是不仅要知道它做什么，还要知道它遵循什么原则。
以下是 Spring 框架的指导原则：

* 提供各个级别的选择。
  Spring 可以尽可能推迟设计决策。
  例如，可以在不更改代码的情况下通过配置切换持久性提供程序。
  对于许多其他基础架构问题以及与第三方 API 的集成也是如此。
* 适应不同的观点。
  Spring 拥有灵活性，对事情应该如何做并不固执己见。
  它从不同的角度支持广泛的应用程序需求。
* 保持强大的向后兼容性。
  对 Spring 的发展进行了精心的管理，以使版本之间几乎没有重大更改。
  Spring 支持精心选择的 JDK 版本与第三方库，
  以方便维护依赖于 Spring 的应用程序与库。
* 关心 API 设计。
  Spring 团队投入了大量的心思与时间来制作直观，并在许多版本与很多年中都适用的 API。
* 为代码质量设置高标准。
  Spring 框架非常强调有意义、最新与准确的 javadoc。
  它是极少数可以声明干净代码结构且程序包之间没有循环依赖关系的项目之一。




[[overview-feedback]]
== 反馈与贡献

对于操作方法问题或诊断或调试问题，建议使用 Stack Overflow。
单击 https://stackoverflow.com/questions/tagged/spring+or+spring-mvc+or+spring-aop+or+spring-jdbc+or+spring-r2dbc+or+spring-transactions+or+spring-annotations+or+spring-jms+or+spring-el+or+spring-test+or+spring+or+spring-remoting+or+spring-orm+or+spring-jmx+or+spring-cache+or+spring-webflux+or+spring-rsocket?tab=Newest[此处]
以获取在 Stack Overflow 上使用的建议标签的列表。
如果相当确定 Spring 框架存在问题或想提出特性，请使用
https://github.com/spring-projects/spring-framework/issues[GitHub Issues]。

如果有解决方案或建议的解决方案，可以在
https://github.com/spring-projects/spring-framework[Github] 上提交拉取请求。
但是，请记住，对于除最琐碎的问题以外的所有问题，都希望在问题跟踪器中记录故障单，
在该跟踪器中进行讨论并保留记录以备将来参考。

有关更多详细信息， 请参见
https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md[CONTRIBUTING]
顶级项目页面上的准则。




[[overview-getting-started]]
== 入门指南

如果刚开始使用 Spring，
那么可能需要通过创建基于
https://projects.spring.io/spring-boot/[Spring Boot]
的应用程序来开始使用 Spring Framework。
Spring Boot 提供了一种快速（且自以为是）的方法来创建可用于生产环境的基于 Spring 的应用程序。
它基于 Spring 框架，更倾向于约定而不是配置，并且旨在尽快启动并运行。

可以使用 https://start.spring.io/[start.spring.io]
生成基本项目，也可以遵循
https://spring.io/guides[“入门”指南]之一，例如
https://spring.io/guides/gs/rest-service/[开始构建 RESTful Web 服务]。
这些指南不仅易于理解，而且非常注重任务，并且大多数都是基于 Spring Boot 的。
它们还涵盖了 Spring 产品组合中的其他项目，在解决特定问题时可能要考虑这些项目。
